Jt 37. Add choice theme report pdf
aalexeen/JRM-Java-Stock-System pull request #106
Opened 2022-10-08 14:41 UTC by saffchen

2022-10-08 21:35 UTC, pelmegov requested changes

2022-10-08 21:35 UTC, pelmegov commented on report/src/main/java/saffchen/Main.java
> +public class Main {
Can it be spring application?

2022-10-08 21:35 UTC, pelmegov commented on report/src/main/java/saffchen/reports/Theme.java
> +    public BaseColor darkTheme() {
It's better to make darkThere and lightTheme subclasses with method getBaseColor, so to be able to hide some specific theme related information.

2022-10-08 21:35 UTC, pelmegov commented on report/src/main/java/saffchen/reports/SwitchTheme.java
> +public class SwitchTheme {
What is a responsibility of this class? It doesn't switch anything.

2022-10-08 21:35 UTC, pelmegov commented on report/src/main/java/saffchen/reports/PDFReportFromFile.java
> +<<<<<<< HEAD
Is this a conflict?

2022-10-09 17:42 UTC, saffchen commented on report/src/main/java/saffchen/reports/PDFReportFromFile.java
> +<<<<<<< HEAD
Resolve

2022-10-09 17:43 UTC, saffchen commented on report/src/main/java/saffchen/Main.java
> +public class Main {
Forgot delete this class. Fixed

2022-10-23 12:20 UTC, saffchen commented on report/src/main/java/saffchen/reports/SwitchTheme.java
> +public class SwitchTheme {
Fixed

2022-10-23 12:20 UTC, saffchen commented on report/src/main/java/saffchen/reports/Theme.java
> +    public BaseColor darkTheme() {
Fixed

2022-10-23 21:09 UTC, pelmegov approved these changes

2022-10-24 18:14 UTC, merged